### ISSUE TITLE
Big Sur?

### ISSUE THREAD

**Issue by aaronjensen** [frarees/typometer#1]
Thank you for taking this over and adding to it. I just came back to try this out and when it attempts to insert the reference pattern nothing actually happens. Did Big Sur perhaps break this?

**Comment by frarees** [comment]
@aaronjensen sorry I've missed this message.

> when it attempts to insert the reference pattern nothing actually happens

Lack of permissions can go unnoticed. You need to give it [screen recording permissions](https://support.apple.com/en-gb/guide/mac-help/mchld6aa7d23/mac).

I usually open typometer via `java -jar typometer-1.1.0.jar`, so I give Terminal.app said permissions.

**Comment by aaronjensen** [comment]
@frarees Ah, that fixed it for me. FWIW, I just tried on a new computer by double clicking on the jar and I never got the prompt. Giving iterm2 the permission explicitly and then running from there as you suggested did work. Thank you!

**Comment by frarees** [comment]
You’re welcome :)

You might be able to give perms to the java executable too. Open typometer, right click on its dock icon, show in finder. You’ll see java. Give it perms too and I think you’ll be able to make it work on double-clicking the jar.

**Comment by ychin** [comment]
I wonder if we could package this as a macOS app bundle. This way it could have its own proper entitlements etc and you don't need to rely on assigning permission to the terminal (which does scare me a little bit). Would take a little bit of work but not too much.
